const canvas = document.getElementById("boardCanvas");
const ctx = canvas.getContext("2d");
const modeSelect = document.getElementById("modeSelect");
const gameTypeSelect = document.getElementById("gameTypeSelect");
const difficultySelect = document.getElementById("difficultySelect");
const undoBtn = document.getElementById("undoBtn");
const resetBtn = document.getElementById("resetBtn");
const soundToggle = document.getElementById("soundToggle");
const bgmToggle = document.getElementById("bgmToggle");
const bgmStyleSelect = document.getElementById("bgmStyleSelect");
const bgmVolume = document.getElementById("bgmVolume");
const statusText = document.getElementById("statusText");
const turnDot = document.getElementById("turnDot");
const celebration = document.getElementById("celebration");
const confettiLayer = document.getElementById("confettiLayer");
const winnerBanner = document.getElementById("winnerBanner");
const gameTitle = document.getElementById("gameTitle");

let board = [];
let currentPlayer = BLACK;
let gameOver = false;
let mode = modeSelect.value;
let difficulty = difficultySelect.value;
let gameType = gameTypeSelect.value;
let BOARD_SIZE = gameType === "connect6" ? 19 : 15;
let winLength = gameType === "connect6" ? 6 : 5;
let stonesLeftThisTurn = 1;
let cellSize = canvas.width / (BOARD_SIZE + 1);
let moveHistory = [];
let blinkOn = true;
let aiTimerId = null;
let audioCtx = null;
let bgmTimerId = null;
let bgmStep = 0;
let bgmStyle = "happy";
let bgmVolumeValue = 0.36;
